///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NGTTestAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NGTTestAutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
    [RepositoryFolder("3936ed74-78e9-40c3-8819-a806f6a02759")]
    public partial class NGTTestAutomationRepository : RepoGenBaseFolder
    {
        static NGTTestAutomationRepository instance = new NGTTestAutomationRepository();
        NGTTestAutomationRepositoryFolders.Generic_appFolder _generic_app;
        NGTTestAutomationRepositoryFolders.NewObjectAppFolder _newobject;
        NGTTestAutomationRepositoryFolders.CustomQmlWindowAppFolder _customqmlwindow;
        NGTTestAutomationRepositoryFolders.FileAppFolder _file;

        /// <summary>
        /// Gets the singleton class instance representing the NGTTestAutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("3936ed74-78e9-40c3-8819-a806f6a02759")]
        public static NGTTestAutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NGTTestAutomationRepository() 
            : base("NGTTestAutomationRepository", "/", null, 0, false, "3936ed74-78e9-40c3-8819-a806f6a02759", ".\\RepositoryImages\\NGTTestAutomationRepository3936ed74.rximgres")
        {
            _generic_app = new NGTTestAutomationRepositoryFolders.Generic_appFolder(this);
            _newobject = new NGTTestAutomationRepositoryFolders.NewObjectAppFolder(this);
            _customqmlwindow = new NGTTestAutomationRepositoryFolders.CustomQmlWindowAppFolder(this);
            _file = new NGTTestAutomationRepositoryFolders.FileAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3936ed74-78e9-40c3-8819-a806f6a02759")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Generic_app folder.
        /// </summary>
        [RepositoryFolder("93361d51-0696-4bc6-ad9c-da0b2fce19b3")]
        public virtual NGTTestAutomationRepositoryFolders.Generic_appFolder Generic_app
        {
            get { return _generic_app; }
        }

        /// <summary>
        /// The NewObject folder.
        /// </summary>
        [RepositoryFolder("aa5aa6d5-a618-42d7-8544-fea132a24ccb")]
        public virtual NGTTestAutomationRepositoryFolders.NewObjectAppFolder NewObject
        {
            get { return _newobject; }
        }

        /// <summary>
        /// The CustomQmlWindow folder.
        /// </summary>
        [RepositoryFolder("cd6e7fa1-8b47-4ac9-a60a-ec7976a68ae0")]
        public virtual NGTTestAutomationRepositoryFolders.CustomQmlWindowAppFolder CustomQmlWindow
        {
            get { return _customqmlwindow; }
        }

        /// <summary>
        /// The File folder.
        /// </summary>
        [RepositoryFolder("19d79684-b65e-461c-9325-b4a1a589be43")]
        public virtual NGTTestAutomationRepositoryFolders.FileAppFolder File
        {
            get { return _file; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
    public partial class NGTTestAutomationRepositoryFolders
    {
        /// <summary>
        /// The Generic_appFolder folder.
        /// </summary>
        [RepositoryFolder("93361d51-0696-4bc6-ad9c-da0b2fce19b3")]
        public partial class Generic_appFolder : RepoGenBaseFolder
        {
            NGTTestAutomationRepositoryFolders.MainWindowAppFolder _mainwindow;
            NGTTestAutomationRepositoryFolders.MainWindow1AppFolder _mainwindow1;

            /// <summary>
            /// Creates a new Generic_app  folder.
            /// </summary>
            public Generic_appFolder(RepoGenBaseFolder parentFolder) :
                    base("Generic_app", "", parentFolder, 0, null, false, "93361d51-0696-4bc6-ad9c-da0b2fce19b3", "")
            {
                _mainwindow = new NGTTestAutomationRepositoryFolders.MainWindowAppFolder(this);
                _mainwindow1 = new NGTTestAutomationRepositoryFolders.MainWindow1AppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("93361d51-0696-4bc6-ad9c-da0b2fce19b3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainWindow folder.
            /// </summary>
            [RepositoryFolder("cd35dc4e-e230-4536-a27e-ebaa15eecd9e")]
            public virtual NGTTestAutomationRepositoryFolders.MainWindowAppFolder MainWindow
            {
                get { return _mainwindow; }
            }

            /// <summary>
            /// The MainWindow1 folder.
            /// </summary>
            [RepositoryFolder("4a398a01-4bb3-49f5-9d5f-2edfcbaf04dd")]
            public virtual NGTTestAutomationRepositoryFolders.MainWindow1AppFolder MainWindow1
            {
                get { return _mainwindow1; }
            }
        }

        /// <summary>
        /// The MainWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd35dc4e-e230-4536-a27e-ebaa15eecd9e")]
        public partial class MainWindowAppFolder : RepoGenBaseFolder
        {
            NGTTestAutomationRepositoryFolders.WGListViewFolder _wglistview;
            NGTTestAutomationRepositoryFolders.ListFolder _list;
            NGTTestAutomationRepositoryFolders.WGVector31Folder _wgvector31;
            RepoItemInfo _expandiconarea1Info;
            RepoItemInfo _wgtextboxframeInfo;
            RepoItemInfo _wgbuttonframeInfo;
            RepoItemInfo _propertytreetest1Info;
            RepoItemInfo _minimizeInfo;
            RepoItemInfo _restoreInfo;
            RepoItemInfo _newobjectInfo;
            RepoItemInfo _scenebrowserInfo;
            RepoItemInfo _showmodaldialogInfo;

            /// <summary>
            /// Creates a new MainWindow  folder.
            /// </summary>
            public MainWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainWindow", "/form[@objectname='MainWindow']", parentFolder, 60000, null, true, "cd35dc4e-e230-4536-a27e-ebaa15eecd9e", "")
            {
                _wglistview = new NGTTestAutomationRepositoryFolders.WGListViewFolder(this);
                _list = new NGTTestAutomationRepositoryFolders.ListFolder(this);
                _wgvector31 = new NGTTestAutomationRepositoryFolders.WGVector31Folder(this);
                _expandiconarea1Info = new RepoItemInfo(this, "ExpandIconArea1", "container[3]//list/list[@name='WGListView']/list[2]/container[1]", 30000, null, "c7ee06dd-9931-47d1-b632-57957e3b6489");
                _wgtextboxframeInfo = new RepoItemInfo(this, "WGTextBoxFrame", "container[3]//list[@name='WGListView']/list[@name='WGListView']/list[1]/list[2]//container[@name='WGTextBoxFrame']", 30000, null, "a91fe9bb-237b-4692-a2f1-09a2d5b02802");
                _wgbuttonframeInfo = new RepoItemInfo(this, "WGButtonFrame", "container[3]//list/list[@name='WGListView']/list[1]/list[8]//element[@name='WGSpinBox']/container[1]", 30000, null, "c2060909-7a9a-4143-afb9-4f258e97afc5");
                _propertytreetest1Info = new RepoItemInfo(this, "PropertyTreeTest1", "?/?/tabpage[@index='7']", 30000, null, "5e855b1d-a287-4e18-bc92-c3af076fbe62");
                _minimizeInfo = new RepoItemInfo(this, "Minimize", "?/?/button[@accessiblename='Minimize']", 30000, null, "4359380c-0e8b-46e6-ac19-de0bd6ea5308");
                _restoreInfo = new RepoItemInfo(this, "Restore", "?/?/button[@accessiblename='Restore']", 30000, null, "81fdc637-4c07-4ef8-93f6-8fbc17816e0e");
                _newobjectInfo = new RepoItemInfo(this, "NewObject", "?/?/menuitem[@text='New Object']", 30000, null, "2cd6e6bc-c107-4870-a47b-25b966cbf1f0");
                _scenebrowserInfo = new RepoItemInfo(this, "SceneBrowser", "?/?/tabpage[@title='SceneBrowser']", 30000, null, "1dcfe234-8cac-4921-988a-61e928a4d82a");
                _showmodaldialogInfo = new RepoItemInfo(this, "ShowModalDialog", "?/?/button[@text='ShowModalDialog']", 30000, null, "47c07d18-dc0c-4e81-9adf-5b49c4c133a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd35dc4e-e230-4536-a27e-ebaa15eecd9e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd35dc4e-e230-4536-a27e-ebaa15eecd9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExpandIconArea1 item.
            /// </summary>
            [RepositoryItem("c7ee06dd-9931-47d1-b632-57957e3b6489")]
            public virtual Ranorex.Container ExpandIconArea1
            {
                get
                {
                    return _expandiconarea1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ExpandIconArea1 item info.
            /// </summary>
            [RepositoryItemInfo("c7ee06dd-9931-47d1-b632-57957e3b6489")]
            public virtual RepoItemInfo ExpandIconArea1Info
            {
                get
                {
                    return _expandiconarea1Info;
                }
            }

            /// <summary>
            /// The WGTextBoxFrame item.
            /// </summary>
            [RepositoryItem("a91fe9bb-237b-4692-a2f1-09a2d5b02802")]
            public virtual Ranorex.Container WGTextBoxFrame
            {
                get
                {
                    return _wgtextboxframeInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WGTextBoxFrame item info.
            /// </summary>
            [RepositoryItemInfo("a91fe9bb-237b-4692-a2f1-09a2d5b02802")]
            public virtual RepoItemInfo WGTextBoxFrameInfo
            {
                get
                {
                    return _wgtextboxframeInfo;
                }
            }

            /// <summary>
            /// The WGButtonFrame item.
            /// </summary>
            [RepositoryItem("c2060909-7a9a-4143-afb9-4f258e97afc5")]
            public virtual Ranorex.Container WGButtonFrame
            {
                get
                {
                    return _wgbuttonframeInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WGButtonFrame item info.
            /// </summary>
            [RepositoryItemInfo("c2060909-7a9a-4143-afb9-4f258e97afc5")]
            public virtual RepoItemInfo WGButtonFrameInfo
            {
                get
                {
                    return _wgbuttonframeInfo;
                }
            }

            /// <summary>
            /// The PropertyTreeTest1 item.
            /// </summary>
            [RepositoryItem("5e855b1d-a287-4e18-bc92-c3af076fbe62")]
            public virtual Ranorex.TabPage PropertyTreeTest1
            {
                get
                {
                    return _propertytreetest1Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The PropertyTreeTest1 item info.
            /// </summary>
            [RepositoryItemInfo("5e855b1d-a287-4e18-bc92-c3af076fbe62")]
            public virtual RepoItemInfo PropertyTreeTest1Info
            {
                get
                {
                    return _propertytreetest1Info;
                }
            }

            /// <summary>
            /// The Minimize item.
            /// </summary>
            [RepositoryItem("4359380c-0e8b-46e6-ac19-de0bd6ea5308")]
            public virtual Ranorex.Button Minimize
            {
                get
                {
                    return _minimizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Minimize item info.
            /// </summary>
            [RepositoryItemInfo("4359380c-0e8b-46e6-ac19-de0bd6ea5308")]
            public virtual RepoItemInfo MinimizeInfo
            {
                get
                {
                    return _minimizeInfo;
                }
            }

            /// <summary>
            /// The Restore item.
            /// </summary>
            [RepositoryItem("81fdc637-4c07-4ef8-93f6-8fbc17816e0e")]
            public virtual Ranorex.Button Restore
            {
                get
                {
                    return _restoreInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Restore item info.
            /// </summary>
            [RepositoryItemInfo("81fdc637-4c07-4ef8-93f6-8fbc17816e0e")]
            public virtual RepoItemInfo RestoreInfo
            {
                get
                {
                    return _restoreInfo;
                }
            }

            /// <summary>
            /// The NewObject item.
            /// </summary>
            [RepositoryItem("2cd6e6bc-c107-4870-a47b-25b966cbf1f0")]
            public virtual Ranorex.MenuItem NewObject
            {
                get
                {
                    return _newobjectInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewObject item info.
            /// </summary>
            [RepositoryItemInfo("2cd6e6bc-c107-4870-a47b-25b966cbf1f0")]
            public virtual RepoItemInfo NewObjectInfo
            {
                get
                {
                    return _newobjectInfo;
                }
            }

            /// <summary>
            /// The SceneBrowser item.
            /// </summary>
            [RepositoryItem("1dcfe234-8cac-4921-988a-61e928a4d82a")]
            public virtual Ranorex.TabPage SceneBrowser
            {
                get
                {
                    return _scenebrowserInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The SceneBrowser item info.
            /// </summary>
            [RepositoryItemInfo("1dcfe234-8cac-4921-988a-61e928a4d82a")]
            public virtual RepoItemInfo SceneBrowserInfo
            {
                get
                {
                    return _scenebrowserInfo;
                }
            }

            /// <summary>
            /// The ShowModalDialog item.
            /// </summary>
            [RepositoryItem("47c07d18-dc0c-4e81-9adf-5b49c4c133a2")]
            public virtual Ranorex.Button ShowModalDialog
            {
                get
                {
                    return _showmodaldialogInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ShowModalDialog item info.
            /// </summary>
            [RepositoryItemInfo("47c07d18-dc0c-4e81-9adf-5b49c4c133a2")]
            public virtual RepoItemInfo ShowModalDialogInfo
            {
                get
                {
                    return _showmodaldialogInfo;
                }
            }

            /// <summary>
            /// The WGListView folder.
            /// </summary>
            [RepositoryFolder("42a637e0-024f-4a7f-8b3d-944655bd0321")]
            public virtual NGTTestAutomationRepositoryFolders.WGListViewFolder WGListView
            {
                get { return _wglistview; }
            }

            /// <summary>
            /// The List folder.
            /// </summary>
            [RepositoryFolder("5eb0818f-453f-498b-a715-fcb59d743884")]
            public virtual NGTTestAutomationRepositoryFolders.ListFolder List
            {
                get { return _list; }
            }

            /// <summary>
            /// The WGVector31 folder.
            /// </summary>
            [RepositoryFolder("7ab57e1f-167b-49ae-9d1b-74ee06b3b637")]
            public virtual NGTTestAutomationRepositoryFolders.WGVector31Folder WGVector31
            {
                get { return _wgvector31; }
            }
        }

        /// <summary>
        /// The WGListViewFolder folder.
        /// </summary>
        [RepositoryFolder("42a637e0-024f-4a7f-8b3d-944655bd0321")]
        public partial class WGListViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _wglistviewrowdelegateInfo;
            RepoItemInfo _wglistviewrowdelegate1Info;
            RepoItemInfo _wglistviewrowdelegate2Info;

            /// <summary>
            /// Creates a new WGListView  folder.
            /// </summary>
            public WGListViewFolder(RepoGenBaseFolder parentFolder) :
                    base("WGListView", "container[3]//list/list[@name='WGListView']/list[1]", parentFolder, 30000, null, false, "42a637e0-024f-4a7f-8b3d-944655bd0321", "")
            {
                _wglistviewrowdelegateInfo = new RepoItemInfo(this, "WGListViewRowDelegate", "element[4]", 30000, null, "e2057148-67c4-4cd1-9d01-23343e367e28");
                _wglistviewrowdelegate1Info = new RepoItemInfo(this, "WGListViewRowDelegate1", "element[6]", 30000, null, "8ab11a00-59a9-48bf-8c22-418d0f8102ba");
                _wglistviewrowdelegate2Info = new RepoItemInfo(this, "WGListViewRowDelegate2", "element[7]", 30000, null, "404f5671-874a-4d0c-a3a0-d9c6dca0e8d6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42a637e0-024f-4a7f-8b3d-944655bd0321")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42a637e0-024f-4a7f-8b3d-944655bd0321")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate item.
            /// </summary>
            [RepositoryItem("e2057148-67c4-4cd1-9d01-23343e367e28")]
            public virtual Ranorex.Unknown WGListViewRowDelegate
            {
                get
                {
                    return _wglistviewrowdelegateInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate item info.
            /// </summary>
            [RepositoryItemInfo("e2057148-67c4-4cd1-9d01-23343e367e28")]
            public virtual RepoItemInfo WGListViewRowDelegateInfo
            {
                get
                {
                    return _wglistviewrowdelegateInfo;
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate1 item.
            /// </summary>
            [RepositoryItem("8ab11a00-59a9-48bf-8c22-418d0f8102ba")]
            public virtual Ranorex.Unknown WGListViewRowDelegate1
            {
                get
                {
                    return _wglistviewrowdelegate1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate1 item info.
            /// </summary>
            [RepositoryItemInfo("8ab11a00-59a9-48bf-8c22-418d0f8102ba")]
            public virtual RepoItemInfo WGListViewRowDelegate1Info
            {
                get
                {
                    return _wglistviewrowdelegate1Info;
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate2 item.
            /// </summary>
            [RepositoryItem("404f5671-874a-4d0c-a3a0-d9c6dca0e8d6")]
            public virtual Ranorex.Unknown WGListViewRowDelegate2
            {
                get
                {
                    return _wglistviewrowdelegate2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate2 item info.
            /// </summary>
            [RepositoryItemInfo("404f5671-874a-4d0c-a3a0-d9c6dca0e8d6")]
            public virtual RepoItemInfo WGListViewRowDelegate2Info
            {
                get
                {
                    return _wglistviewrowdelegate2Info;
                }
            }
        }

        /// <summary>
        /// The ListFolder folder.
        /// </summary>
        [RepositoryFolder("5eb0818f-453f-498b-a715-fcb59d743884")]
        public partial class ListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _wglistviewrowdelegate1Info;
            RepoItemInfo _wglistviewrowdelegate2Info;
            RepoItemInfo _textobject3Info;
            RepoItemInfo _textobject4Info;

            /// <summary>
            /// Creates a new List  folder.
            /// </summary>
            public ListFolder(RepoGenBaseFolder parentFolder) :
                    base("List", "container[@objectname='plg_demo_test/demo_list_panel.qml']//list[@name='list']", parentFolder, 30000, null, false, "5eb0818f-453f-498b-a715-fcb59d743884", "")
            {
                _wglistviewrowdelegate1Info = new RepoItemInfo(this, "WGListViewRowDelegate1", "element[2]", 30000, null, "a03150e7-3b44-4baa-9d4d-426704fb6591");
                _wglistviewrowdelegate2Info = new RepoItemInfo(this, "WGListViewRowDelegate2", "element[3]", 30000, null, "e3e7bca3-0c54-4bff-ae3b-babb690d374e");
                _textobject3Info = new RepoItemInfo(this, "TextObject3", "list[3]/text[@caption=' object3 ']", 30000, null, "725ba839-7ed5-4c6b-bee2-721c00784f03");
                _textobject4Info = new RepoItemInfo(this, "TextObject4", "list[4]/text[@caption=' object4 ']", 30000, null, "04fae0d4-7f29-423a-ba20-cbf40004e079");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5eb0818f-453f-498b-a715-fcb59d743884")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5eb0818f-453f-498b-a715-fcb59d743884")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate1 item.
            /// </summary>
            [RepositoryItem("a03150e7-3b44-4baa-9d4d-426704fb6591")]
            public virtual Ranorex.Unknown WGListViewRowDelegate1
            {
                get
                {
                    return _wglistviewrowdelegate1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate1 item info.
            /// </summary>
            [RepositoryItemInfo("a03150e7-3b44-4baa-9d4d-426704fb6591")]
            public virtual RepoItemInfo WGListViewRowDelegate1Info
            {
                get
                {
                    return _wglistviewrowdelegate1Info;
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate2 item.
            /// </summary>
            [RepositoryItem("e3e7bca3-0c54-4bff-ae3b-babb690d374e")]
            public virtual Ranorex.Unknown WGListViewRowDelegate2
            {
                get
                {
                    return _wglistviewrowdelegate2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The WGListViewRowDelegate2 item info.
            /// </summary>
            [RepositoryItemInfo("e3e7bca3-0c54-4bff-ae3b-babb690d374e")]
            public virtual RepoItemInfo WGListViewRowDelegate2Info
            {
                get
                {
                    return _wglistviewrowdelegate2Info;
                }
            }

            /// <summary>
            /// The TextObject3 item.
            /// </summary>
            [RepositoryItem("725ba839-7ed5-4c6b-bee2-721c00784f03")]
            public virtual Ranorex.Text TextObject3
            {
                get
                {
                    return _textobject3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextObject3 item info.
            /// </summary>
            [RepositoryItemInfo("725ba839-7ed5-4c6b-bee2-721c00784f03")]
            public virtual RepoItemInfo TextObject3Info
            {
                get
                {
                    return _textobject3Info;
                }
            }

            /// <summary>
            /// The TextObject4 item.
            /// </summary>
            [RepositoryItem("04fae0d4-7f29-423a-ba20-cbf40004e079")]
            public virtual Ranorex.Text TextObject4
            {
                get
                {
                    return _textobject4Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextObject4 item info.
            /// </summary>
            [RepositoryItemInfo("04fae0d4-7f29-423a-ba20-cbf40004e079")]
            public virtual RepoItemInfo TextObject4Info
            {
                get
                {
                    return _textobject4Info;
                }
            }
        }

        /// <summary>
        /// The WGVector31Folder folder.
        /// </summary>
        [RepositoryFolder("7ab57e1f-167b-49ae-9d1b-74ee06b3b637")]
        public partial class WGVector31Folder : RepoGenBaseFolder
        {
            RepoItemInfo _arrowtext1Info;

            /// <summary>
            /// Creates a new WGVector31  folder.
            /// </summary>
            public WGVector31Folder(RepoGenBaseFolder parentFolder) :
                    base("WGVector31", "container[@objectname='plg_demo_test/demo_property_panel.qml']//list[@objectname='WGListView']/list[@objectname='WGListView']/list[12]/container[@objectname='WGVector3']", parentFolder, 30000, null, false, "7ab57e1f-167b-49ae-9d1b-74ee06b3b637", "")
            {
                _arrowtext1Info = new RepoItemInfo(this, "ArrowText1", ".//element[@name='WGNumberBox' and @accessiblename='-3.000']/container[1]/text[@name='arrowText']", 30000, null, "4fd3011b-878e-408c-992a-ac8926c0916e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ab57e1f-167b-49ae-9d1b-74ee06b3b637")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ab57e1f-167b-49ae-9d1b-74ee06b3b637")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ArrowText1 item.
            /// </summary>
            [RepositoryItem("4fd3011b-878e-408c-992a-ac8926c0916e")]
            public virtual Ranorex.Text ArrowText1
            {
                get
                {
                    return _arrowtext1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ArrowText1 item info.
            /// </summary>
            [RepositoryItemInfo("4fd3011b-878e-408c-992a-ac8926c0916e")]
            public virtual RepoItemInfo ArrowText1Info
            {
                get
                {
                    return _arrowtext1Info;
                }
            }
        }

        /// <summary>
        /// The MainWindow1AppFolder folder.
        /// </summary>
        [RepositoryFolder("4a398a01-4bb3-49f5-9d5f-2edfcbaf04dd")]
        public partial class MainWindow1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _file1Info;

            /// <summary>
            /// Creates a new MainWindow1  folder.
            /// </summary>
            public MainWindow1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainWindow1", "/form[@objectname='MainWindow']", parentFolder, 30000, null, true, "4a398a01-4bb3-49f5-9d5f-2edfcbaf04dd", "")
            {
                _file1Info = new RepoItemInfo(this, "File1", "?/?/menuitem[@text='File']", 30000, null, "70f9d447-fc59-4164-a97c-9d2685f7401a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4a398a01-4bb3-49f5-9d5f-2edfcbaf04dd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4a398a01-4bb3-49f5-9d5f-2edfcbaf04dd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File1 item.
            /// </summary>
            [RepositoryItem("70f9d447-fc59-4164-a97c-9d2685f7401a")]
            public virtual Ranorex.MenuItem File1
            {
                get
                {
                    return _file1Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File1 item info.
            /// </summary>
            [RepositoryItemInfo("70f9d447-fc59-4164-a97c-9d2685f7401a")]
            public virtual RepoItemInfo File1Info
            {
                get
                {
                    return _file1Info;
                }
            }
        }

        /// <summary>
        /// The NewObjectAppFolder folder.
        /// </summary>
        [RepositoryFolder("aa5aa6d5-a618-42d7-8544-fea132a24ccb")]
        public partial class NewObjectAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newobjectInfo;

            /// <summary>
            /// Creates a new NewObject  folder.
            /// </summary>
            public NewObjectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewObject", "/contextmenu[@objectname='New Object']", parentFolder, 30000, null, true, "aa5aa6d5-a618-42d7-8544-fea132a24ccb", "")
            {
                _newobjectInfo = new RepoItemInfo(this, "NewObject", "menuitem[2]", 30000, null, "3dd3fb65-4efa-4ca8-ac8c-1f5e4fb50d51");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aa5aa6d5-a618-42d7-8544-fea132a24ccb")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aa5aa6d5-a618-42d7-8544-fea132a24ccb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewObject item.
            /// </summary>
            [RepositoryItem("3dd3fb65-4efa-4ca8-ac8c-1f5e4fb50d51")]
            public virtual Ranorex.MenuItem NewObject
            {
                get
                {
                    return _newobjectInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewObject item info.
            /// </summary>
            [RepositoryItemInfo("3dd3fb65-4efa-4ca8-ac8c-1f5e4fb50d51")]
            public virtual RepoItemInfo NewObjectInfo
            {
                get
                {
                    return _newobjectInfo;
                }
            }
        }

        /// <summary>
        /// The CustomQmlWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd6e7fa1-8b47-4ac9-a60a-ec7976a68ae0")]
        public partial class CustomQmlWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new CustomQmlWindow  folder.
            /// </summary>
            public CustomQmlWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CustomQmlWindow", "/form[@title='Custom Qml Window']", parentFolder, 30000, null, true, "cd6e7fa1-8b47-4ac9-a60a-ec7976a68ae0", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", "element[@type='QQuickItem']//container[@objectname='WGExpandingRowLayout']/button[@text='Ok']", 30000, null, "759aad40-286c-40ca-99c9-dadb09239706");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd6e7fa1-8b47-4ac9-a60a-ec7976a68ae0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd6e7fa1-8b47-4ac9-a60a-ec7976a68ae0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("759aad40-286c-40ca-99c9-dadb09239706")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("759aad40-286c-40ca-99c9-dadb09239706")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The FileAppFolder folder.
        /// </summary>
        [RepositoryFolder("19d79684-b65e-461c-9325-b4a1a589be43")]
        public partial class FileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _exitInfo;

            /// <summary>
            /// Creates a new File  folder.
            /// </summary>
            public FileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("File", "/contextmenu[@objectname='File']", parentFolder, 30000, null, true, "19d79684-b65e-461c-9325-b4a1a589be43", "")
            {
                _exitInfo = new RepoItemInfo(this, "Exit", "menuitem[@text='E&xit']", 30000, null, "8e9b3663-82f0-4113-ac93-6e1535ffa1a3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("19d79684-b65e-461c-9325-b4a1a589be43")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("19d79684-b65e-461c-9325-b4a1a589be43")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("8e9b3663-82f0-4113-ac93-6e1535ffa1a3")]
            public virtual Ranorex.MenuItem Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("8e9b3663-82f0-4113-ac93-6e1535ffa1a3")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}