///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SimpleCasesMultipleSelect recording.
    /// </summary>
    [TestModule("681b404c-ceac-4ddc-9f64-e4e6cda5ff71", ModuleType.Recording, 1)]
    public partial class SimpleCasesMultipleSelect : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomationRepository repo = NGTTestAutomationRepository.Instance;

        static SimpleCasesMultipleSelect instance = new SimpleCasesMultipleSelect();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SimpleCasesMultipleSelect()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SimpleCasesMultipleSelect Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey Down}'.", new RecordItemIndex(0));
            Keyboard.Press("{LShiftKey Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.WGListView.WGListViewRowDelegate' at CenterLeft.", repo.MainWindow.WGListView.WGListViewRowDelegateInfo, new RecordItemIndex(1));
            repo.MainWindow.WGListView.WGListViewRowDelegate.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.WGListView.WGListViewRowDelegate1' at CenterLeft.", repo.MainWindow.WGListView.WGListViewRowDelegate1Info, new RecordItemIndex(2));
            repo.MainWindow.WGListView.WGListViewRowDelegate1.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.WGListView.WGListViewRowDelegate2' at CenterLeft.", repo.MainWindow.WGListView.WGListViewRowDelegate2Info, new RecordItemIndex(3));
            repo.MainWindow.WGListView.WGListViewRowDelegate2.Click(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey 1}'.", new RecordItemIndex(4));
            Keyboard.Press("{LShiftKey 1}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
