///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AB_layout_validation recording.
    /// </summary>
    [TestModule("cc3d5e49-cc6f-47b1-a6af-3c7f0c9874c0", ModuleType.Recording, 1)]
    public partial class AB_layout_validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static AB_layout_validation instance = new AB_layout_validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AB_layout_validation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AB_layout_validation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot5' with region {X=0,Y=0,Width=1178,Height=1024}) on item 'Generic_app.MainWindow.AssetBrowser'.", repo.Generic_app.MainWindow.AssetBrowserInfo, new RecordItemIndex(0));
            Validate.ContainsImage(repo.Generic_app.MainWindow.AssetBrowserInfo, AssetBrowser_Screenshot5, AssetBrowser_Screenshot5_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
        CompressedImage AssetBrowser_Screenshot5
        { get { return repo.Generic_app.MainWindow.AssetBrowserInfo.GetScreenshot5(new Rectangle(0, 0, 1178, 1024)); } }

        Imaging.FindOptions AssetBrowser_Screenshot5_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
