///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AB_shorcut recording.
    /// </summary>
    [TestModule("7e5abe31-c3fb-454c-951a-e73d1e187c6d", ModuleType.Recording, 1)]
    public partial class AB_shorcut : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static AB_shorcut instance = new AB_shorcut();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AB_shorcut()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AB_shorcut Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Up' Press.", new RecordItemIndex(0));
            Keyboard.Press(System.Windows.Forms.Keys.Up, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Up' Press.", new RecordItemIndex(1));
            Keyboard.Press(System.Windows.Forms.Keys.Up, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Left' Press.", new RecordItemIndex(2));
            Keyboard.Press(System.Windows.Forms.Keys.Left, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=0,Y=0,Width=233,Height=168}) on item 'Generic_app.MainWindow.Column1'.", repo.Generic_app.MainWindow.Column1Info, new RecordItemIndex(3));
            Validate.CompareImage(repo.Generic_app.MainWindow.Column1Info, Column1_Screenshot4, Column1_Screenshot4_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage Column1_Screenshot4
        { get { return repo.Generic_app.MainWindow.Column1Info.GetScreenshot4(new Rectangle(0, 0, 233, 168)); } }

        Imaging.FindOptions Column1_Screenshot4_Options
        { get { return Imaging.FindOptions.Parse("0.8;EdgesSobel;0,0,233,168;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
