///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ViewMenTestDada_validation_true recording.
    /// </summary>
    [TestModule("ec8f7523-c091-4e50-9425-b9b13f6d787e", ModuleType.Recording, 1)]
    public partial class ViewMenTestDada_validation_true : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static ViewMenTestDada_validation_true instance = new ViewMenTestDada_validation_true();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ViewMenTestDada_validation_true()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ViewMenTestDada_validation_true Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.View' at Center.", repo.Generic_app.MainWindow.ViewInfo, new RecordItemIndex(0));
            repo.Generic_app.MainWindow.View.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.Macros'.", repo.Menu.View.MacrosInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.Menu.View.MacrosInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.History'.", repo.Menu.View.HistoryInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.Menu.View.HistoryInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.CustomModelInterface'.", repo.Menu.View.CustomModelInterfaceInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.Menu.View.CustomModelInterfaceInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.ActiveFiltersControlTest'.", repo.Menu.View.ActiveFiltersControlTestInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.Menu.View.ActiveFiltersControlTestInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.ListModelTest'.", repo.Menu.View.ListModelTestInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.Menu.View.ListModelTestInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.ListFilterTest'.", repo.Menu.View.ListFilterTestInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.Menu.View.ListFilterTestInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.TreeModelTest'.", repo.Menu.View.TreeModelTestInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.Menu.View.TreeModelTestInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.WGContextMenuTest'.", repo.Menu.View.WGContextMenuTestInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.Menu.View.WGContextMenuTestInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.PythonTest1'.", repo.Menu.View.PythonTest1Info, new RecordItemIndex(9));
            Validate.Attribute(repo.Menu.View.PythonTest1Info, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.PythonTest2'.", repo.Menu.View.PythonTest2Info, new RecordItemIndex(10));
            Validate.Attribute(repo.Menu.View.PythonTest2Info, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.PrototypeCustomPanel'.", repo.Menu.View.PrototypeCustomPanelInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.Menu.View.PrototypeCustomPanelInfo, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Visible>'True') on item 'Menu.View.PropertyTreeTest1'.", repo.Menu.View.PropertyTreeTest1Info, new RecordItemIndex(12));
            Validate.Attribute(repo.Menu.View.PropertyTreeTest1Info, "Visible", new Regex(Regex.Escape("True")));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
