///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AB_Horizontal_Vertical_toggle recording.
    /// </summary>
    [TestModule("a0032775-d7f5-4c8d-96ef-43d4899a6384", ModuleType.Recording, 1)]
    public partial class AB_Horizontal_Vertical_toggle : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static AB_Horizontal_Vertical_toggle instance = new AB_Horizontal_Vertical_toggle();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AB_Horizontal_Vertical_toggle()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AB_Horizontal_Vertical_toggle Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.BtnAssetBrowserOrientation' at Center.", repo.Generic_app.MainWindow.BtnAssetBrowserOrientationInfo, new RecordItemIndex(0));
            repo.Generic_app.MainWindow.BtnAssetBrowserOrientation.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=1920,Height=250}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(2));
            Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot2, QQuickWidget_AB_Screenshot2_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.BtnAssetBrowserOrientation' at Center.", repo.Generic_app.MainWindow.BtnAssetBrowserOrientationInfo, new RecordItemIndex(3));
            repo.Generic_app.MainWindow.BtnAssetBrowserOrientation.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=1920,Height=250}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(4));
            Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot1, QQuickWidget_AB_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.BtnAssetBrowserHideFolders' at Center.", repo.Generic_app.MainWindow.BtnAssetBrowserHideFoldersInfo, new RecordItemIndex(5));
            repo.Generic_app.MainWindow.BtnAssetBrowserHideFolders.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(6));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot3' with region {X=0,Y=0,Width=1920,Height=250}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(7));
            Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot3, QQuickWidget_AB_Screenshot3_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.BtnAssetBrowserHideFolders' at Center.", repo.Generic_app.MainWindow.BtnAssetBrowserHideFoldersInfo, new RecordItemIndex(8));
            repo.Generic_app.MainWindow.BtnAssetBrowserHideFolders.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=1920,Height=250}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(9));
            Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot1_2, QQuickWidget_AB_Screenshot1_2_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage QQuickWidget_AB_Screenshot2
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot2(new Rectangle(0, 0, 1920, 250)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,1920,250;True;10000000;0ms"); } }

        CompressedImage QQuickWidget_AB_Screenshot1
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot1(new Rectangle(0, 0, 1920, 250)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,1920,250;True;10000000;0ms"); } }

        CompressedImage QQuickWidget_AB_Screenshot3
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot3(new Rectangle(0, 0, 1920, 250)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot3_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,1920,250;True;10000000;0ms"); } }

        CompressedImage QQuickWidget_AB_Screenshot1_2
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot1(new Rectangle(0, 0, 1920, 250)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,1920,250;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
