///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AB_IconSize recording.
    /// </summary>
    [TestModule("11a7a3c6-d73b-46e0-903d-fc6f4f79513d", ModuleType.Recording, 1)]
    public partial class AB_IconSize : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static AB_IconSize instance = new AB_IconSize();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AB_IconSize()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AB_IconSize Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.Button64pxIcons' at 5;5.", repo.Generic_app.MainWindow.Button64pxIconsInfo, new RecordItemIndex(0));
            repo.Generic_app.MainWindow.Button64pxIcons.Click("5;5");
            Delay.Milliseconds(3370);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.FilterText_Search_filter' at 5;4.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(1));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Click(new Location(FilterText_Search_filter_Screenshot1, "5;4", FilterText_Search_filter_Screenshot1_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot4' with region {X=0,Y=3,Width=523,Height=247}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(2));
            Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot4, QQuickWidget_AB_Screenshot4_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.Column2' at 4;5.", repo.Generic_app.MainWindow.Column2Info, new RecordItemIndex(3));
            repo.Generic_app.MainWindow.Column2.Click(new Location(Column2_Screenshot1, "4;5", Column2_Screenshot1_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot5' with region {X=3,Y=0,Width=1917,Height=250}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(4));
            Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot5, QQuickWidget_AB_Screenshot5_Options);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.IconFile2' at 15;7.", repo.Generic_app.MainWindow.IconFile2Info, new RecordItemIndex(5));
            //repo.Generic_app.MainWindow.IconFile2.Click(new Location(IconFile2_Screenshot1, "15;7", IconFile2_Screenshot1_Options));
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot6' with region {X=4,Y=0,Width=1916,Height=250}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(6));
            //Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot6, QQuickWidget_AB_Screenshot6_Options);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.IconFile1' at 14;6.", repo.Generic_app.MainWindow.IconFile1Info, new RecordItemIndex(7));
            //repo.Generic_app.MainWindow.IconFile1.Click(new Location(IconFile1_Screenshot1, "14;6", IconFile1_Screenshot1_Options));
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot7' with region {X=0,Y=0,Width=1920,Height=250}) on item 'Generic_app.MainWindow.QQuickWidget_AB'.", repo.Generic_app.MainWindow.QQuickWidget_ABInfo, new RecordItemIndex(8));
            //Validate.CompareImage(repo.Generic_app.MainWindow.QQuickWidget_ABInfo, QQuickWidget_AB_Screenshot7, QQuickWidget_AB_Screenshot7_Options);
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage FilterText_Search_filter_Screenshot1
        { get { return repo.Generic_app.MainWindow.FilterText_Search_filterInfo.GetScreenshot1(new Rectangle(1772, 5, 23, 13)); } }

        Imaging.FindOptions FilterText_Search_filter_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        CompressedImage QQuickWidget_AB_Screenshot4
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot4(new Rectangle(0, 3, 523, 247)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot4_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,3,523,247;True;10000000;0ms"); } }

        CompressedImage Column2_Screenshot1
        { get { return repo.Generic_app.MainWindow.Column2Info.GetScreenshot1(new Rectangle(1481, 17, 45, 12)); } }

        Imaging.FindOptions Column2_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        CompressedImage QQuickWidget_AB_Screenshot5
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot5(new Rectangle(3, 0, 1917, 250)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot5_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;3,0,1917,250;True;10000000;0ms"); } }

        CompressedImage IconFile2_Screenshot1
        { get { return repo.Generic_app.MainWindow.IconFile2Info.GetScreenshot1(new Rectangle(154, 42, 14, 10)); } }

        Imaging.FindOptions IconFile2_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        CompressedImage QQuickWidget_AB_Screenshot6
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot6(new Rectangle(4, 0, 1916, 250)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot6_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;4,0,1916,250;True;10000000;0ms"); } }

        CompressedImage IconFile1_Screenshot1
        { get { return repo.Generic_app.MainWindow.IconFile1Info.GetScreenshot1(new Rectangle(7, 62, 31, 14)); } }

        Imaging.FindOptions IconFile1_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        CompressedImage QQuickWidget_AB_Screenshot7
        { get { return repo.Generic_app.MainWindow.QQuickWidget_ABInfo.GetScreenshot7(new Rectangle(0, 0, 1920, 250)); } }

        Imaging.FindOptions QQuickWidget_AB_Screenshot7_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,1920,250;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
