///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace NGTTestAutomation.Generic_app_UI
{
    public partial class AB_layout_RHS
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Up_AssetBrowser()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'PlgPanelManagerAssetBrowserPanelQm.AssetBrowser' at 1205;3.", repo.PlgPanelManagerAssetBrowserPanelQm.AssetBrowserInfo);
            repo.PlgPanelManagerAssetBrowserPanelQm.AssetBrowser.MoveTo("1205;3");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void DoDelay1()
        {
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.");
            Delay.Duration(500, false);
        }

        public void Mouse_Move_AssetBrowser()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Generic_app.MainWindow.AssetBrowser' at 1221;3.", repo.Generic_app.MainWindow.AssetBrowserInfo);
            repo.Generic_app.MainWindow.AssetBrowser.MoveTo("1221;3");
        }

        public void DoDelay()
        {
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.");
            Delay.Duration(500, false);
        }

        public void Mouse_Down_AssetBrowser()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Generic_app.MainWindow.AssetBrowser' at 1213;17.", repo.Generic_app.MainWindow.AssetBrowserInfo);
            repo.Generic_app.MainWindow.AssetBrowser.MoveTo("1213;17");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

    }
}