///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AB_Multipl_filter recording.
    /// </summary>
    [TestModule("5bcbbc42-77df-426f-be47-484a6257eaf3", ModuleType.Recording, 1)]
    public partial class AB_Multipl_filter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static AB_Multipl_filter instance = new AB_Multipl_filter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AB_Multipl_filter()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AB_Multipl_filter Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.FilterText_Search_filter' at Center.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(0));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'filter1' on item 'Generic_app.MainWindow.FilterText_Search_filter'.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(1));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Element.SetAttributeValue("Text", "filter1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(2));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.FilterText_Search_filter' at Center.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(3));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'filter2' on item 'Generic_app.MainWindow.FilterText_Search_filter'.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(4));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Element.SetAttributeValue("Text", "filter2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(5));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.FilterText_Search_filter' at Center.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(6));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'filter3' on item 'Generic_app.MainWindow.FilterText_Search_filter'.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(7));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Element.SetAttributeValue("Text", "filter3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(8));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.FilterText_Search_filter' at Center.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(9));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'filter4' on item 'Generic_app.MainWindow.FilterText_Search_filter'.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(10));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Element.SetAttributeValue("Text", "filter4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(11));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.FilterText_Search_filter' at Center.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(12));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'filter5' on item 'Generic_app.MainWindow.FilterText_Search_filter'.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(13));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Element.SetAttributeValue("Text", "filter5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(14));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.FilterText_Search_filter' at Center.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(15));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'filter6' on item 'Generic_app.MainWindow.FilterText_Search_filter'.", repo.Generic_app.MainWindow.FilterText_Search_filterInfo, new RecordItemIndex(16));
            repo.Generic_app.MainWindow.FilterText_Search_filter.Element.SetAttributeValue("Text", "filter6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(17));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
