///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Bool01 recording.
    /// </summary>
    [TestModule("261344bd-8e8a-4165-871c-98bafbf75f2d", ModuleType.Recording, 1)]
    public partial class Bool01 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static Bool01 instance = new Bool01();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Bool01()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Bool01 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.WGListView.WGTextBoxFrame' at Center.", repo.Generic_app.MainWindow.WGListView.WGTextBoxFrameInfo, new RecordItemIndex(0));
            repo.Generic_app.MainWindow.WGListView.WGTextBoxFrame.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(1));
            Delay.Duration(100, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=4,Width=18,Height=16}) on item 'Generic_app.MainWindow.WGListView.Bool'.", repo.Generic_app.MainWindow.WGListView.BoolInfo, new RecordItemIndex(2));
            Validate.CompareImage(repo.Generic_app.MainWindow.WGListView.BoolInfo, Bool_Screenshot1, Bool_Screenshot1_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage Bool_Screenshot1
        { get { return repo.Generic_app.MainWindow.WGListView.BoolInfo.GetScreenshot1(new Rectangle(0, 4, 18, 16)); } }

        Imaging.FindOptions Bool_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.95;EdgesSobel;0,4,18,16;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
