///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LFT_Search recording.
    /// </summary>
    [TestModule("86b4ba44-4d9d-453c-a7c3-eb655af623e2", ModuleType.Recording, 1)]
    public partial class LFT_Search : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static LFT_Search instance = new LFT_Search();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LFT_Search()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LFT_Search Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.LFT_panel.WGTextBox' at Center.", repo.MainWindow.LFT_panel.WGTextBoxInfo, new RecordItemIndex(0));
            repo.MainWindow.LFT_panel.WGTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'affine{Return}'.", new RecordItemIndex(1));
            Keyboard.Press("affine{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating CompareImage (Screenshot: 'Screenshot8' with region {X=0,Y=0,Width=72,Height=22}) on item 'MainWindow.LFT_panel.List'.", repo.MainWindow.LFT_panel.ListInfo, new RecordItemIndex(2));
            Validate.CompareImage(repo.MainWindow.LFT_panel.ListInfo, List_Screenshot8, List_Screenshot8_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage List_Screenshot8
        { get { return repo.MainWindow.LFT_panel.ListInfo.GetScreenshot8(new Rectangle(0, 0, 72, 22)); } }

        Imaging.FindOptions List_Screenshot8_Options
        { get { return Imaging.FindOptions.Parse("0.7;EdgesSobel;0,0,72,22;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
