///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LMT_SwitchModel recording.
    /// </summary>
    [TestModule("1bd606eb-c7e1-45d7-8c91-61a76a4bb58c", ModuleType.Recording, 1)]
    public partial class LMT_SwitchModel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static LMT_SwitchModel instance = new LMT_SwitchModel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LMT_SwitchModel()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LMT_SwitchModel Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.ListModel_Test.SwitchModelOff' at Center.", repo.Generic_app.MainWindow.ListModel_Test.SwitchModelOffInfo, new RecordItemIndex(0));
            repo.Generic_app.MainWindow.ListModel_Test.SwitchModelOff.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=1174,Height=926}) on item 'Generic_app.MainWindow.ListModel_Test.List1'.", repo.Generic_app.MainWindow.ListModel_Test.List1Info, new RecordItemIndex(1));
                Validate.CompareImage(repo.Generic_app.MainWindow.ListModel_Test.List1Info, List1_Screenshot2, List1_Screenshot2_Options, Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            // Disable because of crash jira#
            //Report.Log(ReportLevel.Info, "Mouse", "Disable because of crash jira#\r\nMouse Left Click item 'Generic_app.MainWindow.ListModel_Test.SwitchModelOff' at Center.", repo.Generic_app.MainWindow.ListModel_Test.SwitchModelOffInfo, new RecordItemIndex(2));
            //repo.Generic_app.MainWindow.ListModel_Test.SwitchModelOff.Click();
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage List1_Screenshot2
        { get { return repo.Generic_app.MainWindow.ListModel_Test.List1Info.GetScreenshot2(new Rectangle(0, 0, 1174, 926)); } }

        Imaging.FindOptions List1_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.8;EdgesSobel;0,0,1174,926;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
