///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LMT_SwitchModel recording.
    /// </summary>
    [TestModule("1bd606eb-c7e1-45d7-8c91-61a76a4bb58c", ModuleType.Recording, 1)]
    public partial class LMT_SwitchModel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static LMT_SwitchModel instance = new LMT_SwitchModel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LMT_SwitchModel()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LMT_SwitchModel Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'Generic_app.MainWindow.Aardwolf'.", repo.Generic_app.MainWindow.AardwolfInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.Generic_app.MainWindow.AardwolfInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Generic_app.MainWindow.ListModel_Test.SwitchModelOff' at Center.", repo.Generic_app.MainWindow.ListModel_Test.SwitchModelOffInfo, new RecordItemIndex(1));
            repo.Generic_app.MainWindow.ListModel_Test.SwitchModelOff.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'Generic_app.MainWindow.Aardwolf'.", repo.Generic_app.MainWindow.AardwolfInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.Generic_app.MainWindow.AardwolfInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
