///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NGTTestAutomation.Generic_app_UI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Multicol_Add_Column recording.
    /// </summary>
    [TestModule("413d97ba-2da5-4a2f-91b3-a0f2b67df87f", ModuleType.Recording, 1)]
    public partial class Multicol_Add_Column : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NGTTestAutomation.NGTTestAutomationRepository repository.
        /// </summary>
        public static NGTTestAutomation.NGTTestAutomationRepository repo = NGTTestAutomation.NGTTestAutomationRepository.Instance;

        static Multicol_Add_Column instance = new Multicol_Add_Column();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Multicol_Add_Column()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Multicol_Add_Column Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.AddColumn' at Center.", repo.MainWindow.MultiColumnListTest.AddColumnInfo, new RecordItemIndex(0));
            repo.MainWindow.MultiColumnListTest.AddColumn.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=1174,Height=906}) on item 'MainWindow.MultiColumnListTest.List'.", repo.MainWindow.MultiColumnListTest.ListInfo, new RecordItemIndex(1));
                Validate.ContainsImage(repo.MainWindow.MultiColumnListTest.ListInfo, List_Screenshot1, List_Screenshot1_Options, Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.AddColumn' at Center.", repo.MainWindow.MultiColumnListTest.AddColumnInfo, new RecordItemIndex(2));
            repo.MainWindow.MultiColumnListTest.AddColumn.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=1174,Height=906}) on item 'MainWindow.MultiColumnListTest.List'.", repo.MainWindow.MultiColumnListTest.ListInfo, new RecordItemIndex(3));
                Validate.ContainsImage(repo.MainWindow.MultiColumnListTest.ListInfo, List_Screenshot2, List_Screenshot2_Options, Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.AddColumn' at Center.", repo.MainWindow.MultiColumnListTest.AddColumnInfo, new RecordItemIndex(4));
            repo.MainWindow.MultiColumnListTest.AddColumn.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot3' with region {X=0,Y=0,Width=1174,Height=906}) on item 'MainWindow.MultiColumnListTest.List'.", repo.MainWindow.MultiColumnListTest.ListInfo, new RecordItemIndex(5));
                Validate.ContainsImage(repo.MainWindow.MultiColumnListTest.ListInfo, List_Screenshot3, List_Screenshot3_Options, Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.RemoveColumn' at Center.", repo.MainWindow.MultiColumnListTest.RemoveColumnInfo, new RecordItemIndex(6));
            repo.MainWindow.MultiColumnListTest.RemoveColumn.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.RemoveColumn' at Center.", repo.MainWindow.MultiColumnListTest.RemoveColumnInfo, new RecordItemIndex(7));
            repo.MainWindow.MultiColumnListTest.RemoveColumn.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.RemoveColumn' at Center.", repo.MainWindow.MultiColumnListTest.RemoveColumnInfo, new RecordItemIndex(8));
            repo.MainWindow.MultiColumnListTest.RemoveColumn.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.RemoveColumn' at Center.", repo.MainWindow.MultiColumnListTest.RemoveColumnInfo, new RecordItemIndex(9));
            repo.MainWindow.MultiColumnListTest.RemoveColumn.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.MultiColumnListTest.RemoveColumn' at Center.", repo.MainWindow.MultiColumnListTest.RemoveColumnInfo, new RecordItemIndex(10));
            repo.MainWindow.MultiColumnListTest.RemoveColumn.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating ContainsImage (Screenshot: 'Screenshot4' with region {X=0,Y=0,Width=1174,Height=906}) on item 'MainWindow.MultiColumnListTest.List'.", repo.MainWindow.MultiColumnListTest.ListInfo, new RecordItemIndex(11));
                Validate.ContainsImage(repo.MainWindow.MultiColumnListTest.ListInfo, List_Screenshot4, List_Screenshot4_Options, Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
        }

#region Image Feature Data
        CompressedImage List_Screenshot1
        { get { return repo.MainWindow.MultiColumnListTest.ListInfo.GetScreenshot1(new Rectangle(0, 0, 1174, 906)); } }

        Imaging.FindOptions List_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        CompressedImage List_Screenshot2
        { get { return repo.MainWindow.MultiColumnListTest.ListInfo.GetScreenshot2(new Rectangle(0, 0, 1174, 906)); } }

        Imaging.FindOptions List_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        CompressedImage List_Screenshot3
        { get { return repo.MainWindow.MultiColumnListTest.ListInfo.GetScreenshot3(new Rectangle(0, 0, 1174, 906)); } }

        Imaging.FindOptions List_Screenshot3_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

        CompressedImage List_Screenshot4
        { get { return repo.MainWindow.MultiColumnListTest.ListInfo.GetScreenshot4(new Rectangle(0, 0, 1174, 906)); } }

        Imaging.FindOptions List_Screenshot4_Options
        { get { return Imaging.FindOptions.Parse("0.85;EdgesSobel;0,0,0,0;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
