name  := core_unit_test
type  := unit_test

include $(BW_COMPONENT_HEADER)

cxxSource =							\
	main							\
	test_multi_proc_test_case		\

dependsOn += cstdmf build

include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.rules - core_unit_test/unit_test
