///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Reporting;
using Ranorex.Core.Testing;

namespace NGTTestAutomation.Open_Close
{
    public partial class Teardown_Fail_Pass
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Close_Application_MainWindow()
        {
        	if (Ranorex.Core.Testing.TestCase.Current.Status  != Ranorex.Core.Reporting.ActivityStatus.Success)
        	{
        		Report.Log(ReportLevel.Info, "Application", "(Optional Action)\r\nClosing application containing item 'MainWindow'.", repo.Generic_app.MainWindow.SelfInfo);
          		Host.Local.CloseApplication(repo.Generic_app.MainWindow.Self, 30000);
        	}
          
        }

    }
}